### ISSUE TITLE
Google cloud slack mvp

### ISSUE THREAD

**Issue by posix4e** [posix4e/billbot#1]
Hey everyone, let's do a mvp . Please checkout miserbot to see what it does first before asking questions. @wolfgangihloff did you 
already look at miserbot?

# TODO
- [ ] Create a simple bot (slack)
- [ ] Have it provide basic cloud statistics in a neat way. Checkout miserbot for an example
- [ ] In this case support google cloud instead of AWS like miserbot, but design it so we can add all the clouds later.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.5 ETH (877.49 USD @ $1754.99/ETH)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/posix4e/billbot/1/100025016).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/posix4e/billbot/1/100025016).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.com/invite/83BK5z55yB/'>Gitcoin's Discord</a>
* $2,689,591.10 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by wolfgangihloff** [comment]
This is a bit too generic for me to consider, @posix4e can you elaborate?

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 5 months from now.
Please review their action plans below:


**1) [vkmguy](https://gitcoin.co/vkmguy) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=approve&worker=vkmguy) | [reject worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=reject&worker=vkmguy))_.**

I would like to know about the task. 
Thanks,
vkmguy
**2) [gitofdeepanshu](https://gitcoin.co/gitofdeepanshu) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=approve&worker=gitofdeepanshu) | [reject worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=reject&worker=gitofdeepanshu))_.**

Hey man,
I have good experience with Google cloud and Slack. 
But I am not able to understand what you want exactly.
Please elaborate more and I'll get into it. :)
**3) [manticorevault](https://gitcoin.co/manticorevault) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=approve&worker=manticorevault) | [reject worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=reject&worker=manticorevault))_.**

Hello! I would like to know a bit more about the task exactly! Thank you very much in advance!
**4) [ledicjp](https://gitcoin.co/ledicjp) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=approve&worker=ledicjp) | [reject worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=reject&worker=ledicjp))_.**

Hi Alex,
I'm Josip, I'm a cloud software engineer at IBM Cloud (ironically I've already worked on pricing related stuff for one offering) but I wanted to try out gitcoin today to earn some crypto and this looked like a fun little MVP to build.

My questions to you are:
- How generic is the code you currently have for the AWS integration? What is the problem currently that makes it hard to add other clouds?
- Where do you run your backend? Is it run in a serverless fashion, where a function triggers a slack webhook?
- Do you have knowledge of how to fetch the relevant cost related data from Google cloud or would this be part of my job?
- Are you using node.js? Python?
- How many users do you have? Is this really supposed to be a prototype or something that will have to support hundreds/thousands of users?

My action plan:
- I would definitely start with a research phase, learn about your existing tech stack, code, data. I would suggest that we make the approach more robust by defining a common model that is abstract enough to describe pricing related data of all clouds. Then I would either write a completely separate function for Google cloud or if applicable I would refactor your existing AWS code and reuse it for the Google cloud use case.

Also, I feel like the payment is a little bit on the low side but it depends on what you already have in place, so please come back to me if you're interested before approving anything. I would be happy to work with you.

Best
Josip
**5) [taufiq1991](https://gitcoin.co/taufiq1991) has been approved to start work.**

I am designer,
If you need a designer who has many unique themes, please contact me, 

I also work as a group admin,
I also have a telegram bot 😁
**6) [jjao2003](https://gitcoin.co/jjao2003) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=approve&worker=jjao2003) | [reject worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=reject&worker=jjao2003))_.**

To carryout the task effectively
**7) [rob-lw](https://gitcoin.co/rob-lw) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=approve&worker=rob-lw) | [reject worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=reject&worker=rob-lw))_.**

Hello, Proposed action plan for a simple MVP slack bot.
1.	Implement a Slack bot utilizing the slack slash command 
2.	Integrate with Google Cloud Billing API
3.	Provide notifications of basic billing information to slack
**8) [caperez17](https://gitcoin.co/caperez17) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=approve&worker=caperez17) | [reject worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=reject&worker=caperez17))_.**

Hey, I am really interested in this bounty. I do not have experienced working with backend but I am really interested to learn and learn doing.
**9) [samrahimi](https://gitcoin.co/samrahimi) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=approve&worker=samrahimi) | [reject worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=reject&worker=samrahimi))_.**

I would love to build this for you... will start off by replicating the Miserbot functionality of posting gcloud usage updates to a slack channel and allowing simple queries of usage and cost - I have built slackbots before and have used google cloud compute services and APIs extensively over the years.
**10) [mjosephd](https://gitcoin.co/mjosephd) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=approve&worker=mjosephd) | [reject worker](https://gitcoin.co/issue/posix4e/billbot/1/100025016?mutate_worker_action=reject&worker=mjosephd))_.**

Hi there,

I work at a SAAS cloud-based company and have around 9+ years of experience. I find this a good project to get started on with Gitcoin.

I do however have a couple of questions about the nature of the task.

- Is there an expectation to maintain this project and new features later on? I am more inclined to a handover type of project where I work on the task for your main requirements and hand it over with appropriate documentation.
- Do you already have an infrastructure setup for hosting any backend items (service that pulls the data, etc).
- What is the budget for the infrastructure costs?
- How many users are you expecting to use this, would you be expecting to use this in production immediately (or is a prototype that will be cleaned up by you or someone from your team, etc?)

Plan
- So the first thing is to do some research, come up with an architecture plan on how the system will run. Do this all while figuring out your current infrastructure and how you will host this service. Do some cross-checking on the requirements and once that is finalized start work.
**11) [rastin](https://gitcoin.co/rastin) has been approved to start work.**

Hi Everyone,
I am really interested to work on this project. Please let me know how may I collaborate?

Regards
Rastin

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/posix4e/billbot/1/100025016).

**Comment by jpompe** [comment]
https://github.com/concurrencylabs/aws-cost-analysis

**Comment by wolfgangihloff** [comment]
Is reading this, but I am missing context on what the outcome be. Can you write down the acceptance criteria?

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@rastin Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@rastin Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@rastin Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@rastin Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by Rastin** [comment]
Sorry I got into another project!

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@rastin Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@rastin due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/posix4e/billbot/1/100025016) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@taufiq1991 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@rastin Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@rastin Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)

**Comment by gitcoinbot** [comment]
@rastin Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=1) | [3 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=3) | [5 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=5) | [10 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=10) | [100 days](https://gitcoin.co/issue/posix4e/billbot/1/100025016?snooze=100)
